imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/registrationage/adm/style/images'
            $ext_root_path: '%core.root_path%ext/david63/registrationage/'
        public: true

    david63.registrationage.listener:
        class: david63\registrationage\event\listener
        tags:
            - { name: event.listener }

    david63.registrationage.admin.controller:
        class: david63\registrationage\controller\admin_controller

    david63.registrationage.data.controller:
        class: david63\registrationage\controller\data_controller

    david63.registrationage.core.functions:
        class: david63\registrationage\core\functions

    david63.registrationage.core.ra.functions:
        class: david63\registrationage\core\ra_functions
